### ISSUE TITLE
[VSCode 0.10.10] VS Code 0.10.10 support

### ISSUE THREAD

**Issue by lelong37** [NativeScript/nativescript-vscode-extension#25] opened 2016-03-08 04:06 UTC
Not sure if it's because I updated to 0.10.10 but now getting this error:

![image](https://cloud.githubusercontent.com/assets/4691404/13591714/dce63724-e4b0-11e5-8f45-3d3f14a61596.png)

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch on iOS Device",
			"type": "nativescript",
			"platform": "ios",
			"request": "launch",
			"appRoot": ".",
			"sourceMaps": true,
			"diagnosticLogging": false,
			"stopOnEntry": true,
			"emulator": false
		},
		{
			"name": "Attach on iOS Device",
			"type": "nativescript",
			"platform": "ios",
			"request": "attach",
			"appRoot": ".",
			"sourceMaps": true,
			"diagnosticLogging": false,
			"emulator": false
		},
		{
			"name": "Launch on iOS Emulator",
			"type": "nativescript",
			"platform": "ios",
			"request": "launch",
			"appRoot": ".",
			"sourceMaps": true,
			"diagnosticLogging": false,
			"stopOnEntry": true,
			"emulator": true
		},
		{
			"name": "Attach on iOS Emulator",
			"type": "nativescript",
			"platform": "ios",
			"request": "attach",
			"appRoot": ".",
			"sourceMaps": true,
			"diagnosticLogging": false,
			"emulator": true
		},
		{
			"name": "Launch on Android Device",
			"type": "nativescript",
			"platform": "android",
			"request": "launch",
			"appRoot": ".",
			"sourceMaps": true,
			"diagnosticLogging": false,
			"stopOnEntry": true,
			"emulator": false
		},
		{
			"name": "Launch on Android Emulator",
			"type": "nativescript",
			"platform": "android",
			"request": "launch",
			"appRoot": ".",
			"sourceMaps": true,
			"diagnosticLogging": false,
			"stopOnEntry": true,
			"emulator": true
		},
		{
			"name": "Attach on Android Device",
			"type": "nativescript",
			"platform": "android",
			"request": "attach",
			"appRoot": ".",
			"sourceMaps": false,
			"diagnosticLogging": false,
			"emulator": false
		},
		{
			"name": "Attach on Android Emulator",
			"type": "nativescript",
			"platform": "android",
			"request": "attach",
			"appRoot": ".",
			"sourceMaps": false,
			"diagnosticLogging": false,
			"emulator": true
		}
	]
}
```

**Comment by ivanbuhov** [comment] 2016-03-08 08:35
When does the message show up? Which debug configuration caused this message to show up? Make sure you have the latest extension version by reinstalling it. Also, you can try removing your `launch.json` file and generating it again from the little gear icon in the Debug Panel. If the error is still there, set `diagnosticLogging` to `true` in the debug configuration you are using and send the log in the Debugger Console.

**Comment by lelong37** [comment] 2016-03-08 11:03
Thanks @ivanbuhov, I've uninstalled the VSCode plugin and have deleted the launch.json a few times as well as rebooting. The message shows up on pretty much any debug configuration, I'm using Launch on IOS Emulator most frequently. Will send the log to you first thing tomorrow.

**Comment by ivanbuhov** [comment] 2016-03-08 15:21
Hi @lelong37 
I reproduced the issue. There are some changes in VS Code 0.10.10 which cause this behavior. To fix it, add `"cwd": "${workspaceRoot}"` to every configuration in `launch.json` file.

**Comment by Daxito** [comment] 2016-03-09 03:05
I changed . for ${workspaceRoot} but everytime I add a breakpoint it gives me this error, I also see those warnings, any idea?

![screen shot 2016-03-08 at 9 02 52 pm](https://cloud.githubusercontent.com/assets/16787057/13624146/31e78a64-e571-11e5-9881-c267cf50a48d.png)
![screen shot 2016-03-08 at 9 04 30 pm](https://cloud.githubusercontent.com/assets/16787057/13624175/62453d00-e571-11e5-86a5-e7180a2f1e1c.png)

**Comment by rajarameshvarma** [comment] 2016-03-09 19:03
I have the same issue

**Comment by ivanbuhov** [comment] 2016-03-10 08:29
@Daxito just ignore the warnings, they will be gone in the next version of the extension. We are investigating the other issue ("Unexpected end of input" error message). It seems it will require changes in the extension. Till then, I suggest downgrading to VS Code 0.10.9.

**Comment by lelong37** [comment] 2016-03-10 08:36
@ivanbuhov tried everything, still can't debug, here is the log as requested.

```
CpResource scmobileapp/Resources/sclogo.png build/emulator/scmobileapp.app/sclogo.png
    cd /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/lelong37/.nvm/versions/node/v4.2.1/bin:/Applications/Genymotion\\ Shell.app/Contents/MacOS/:/Applications/Genymotion.app/Contents/MacOS:/Users/lelong37/Library/Android-SDK/platform-tools:/Users/lelong37/Library/Android-SDK/tools:/usr/local/lib/dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin:/Users/lelong37/.dnx/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/scmobileapp/Resources/sclogo.png /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/build/emulator/scmobileapp.app
CpResource scmobileapp/Resources/sclogo@2x.png build/emulator/scmobileapp.app/sclogo@2x.png
    cd /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/lelong37/.nvm/versions/node/v4.2.1/bin:/Applications/Genymotion\\ Shell.app/Contents/MacOS/:/Applications/Genymotion.app/Contents/MacOS:/Users/lelong37/Library/Android-SDK/platform-tools:/Users/lelong37/Library/Android-SDK/tools:/usr/local/lib/dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin:/Users/lelong37/.dnx/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/scmobileapp/Resources/sclogo@2x.png /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/build/emulator/scmobileapp.app
CpResource scmobileapp/Resources/sclogo@3x.png build/emulator/scmobileapp.app/sclogo@3x.png
    cd /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/lelong37/.nvm/versions/node/v4.2.1/bin:/Applications/Genymotion\\ Shell.app/Contents/MacOS/:/Applications/Genymotion.app/Contents/MacOS:/Users/lelong37/Library/Android-SDK/platform-tools:/Users/lelong37/Library/Android-SDK/tools:/usr/local/lib/dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin:/Users/lelong37/.dnx/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/scmobileapp/Resources/sclogo@3x.png /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/build/emulator/scmobileapp.app
CpResource scmobileapp/Resources/splashscreen.9.png build/emulator/scmobileapp.app/splashscreen.9.png
    cd /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/lelong37/.nvm/versions/node/v4.2.1/bin:/Applications/Genymotion\\ Shell.app/Contents/MacOS/:/Applications/Genymotion.app/Contents/MacOS:/Users/lelong37/Library/Android-SDK/platform-tools:/Users/lelong37/Library/Android-SDK/tools:/usr/local/lib/dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin:/Users/lelong37/.dnx/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/scmobileapp/Resources/splashscreen.9.png /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/build/emulator/scmobileapp.app
CpResource scmobileapp/Resources/user_profileimage.png build/emulator/scmobileapp.app/user_profileimage.png
    cd /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/lelong37/.nvm/versions/node/v4.2.1/bin:/Applications/Genymotion\\ Shell.app/Contents/MacOS/:/Applications/Genymotion.app/Contents/MacOS:/Users/lelong37/Library/Android-SDK/platform-tools:/Users/lelong37/Library/Android-SDK/tools:/usr/local/lib/dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin:/Users/lelong37/.dnx/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/scmobileapp/Resources/user_profileimage.png /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/build/emulator/scmobileapp.app
CpResource scmobileapp/Resources/user_profileimage@2x.png build/emulator/scmobileapp.app/user_profileimage@2x.png
    cd /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/lelong37/.nvm/versions/node/v4.2.1/bin:/Applications/Genymotion\\ Shell.app/Contents/MacOS/:/Applications/Genymotion.app/Contents/MacOS:/Users/lelong37/Library/Android-SDK/platform-tools:/Users/lelong37/Library/Android-SDK/tools:/usr/local/lib/dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin:/Users/lelong37/.dnx/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/scmobileapp/Resources/user_profileimage@2x.png /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/build/emulator/scmobileapp.app
  ›CpResource scmobileapp/Resources/user_profileimage@3x.png build/emulator/scmobileapp.app/user_profileimage@3x.png
    cd /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/lelong37/.nvm/versions/node/v4.2.1/bin:/Applications/Genymotion\\ Shell.app/Contents/MacOS/:/Applications/Genymotion.app/Contents/MacOS:/Users/lelong37/Library/Android-SDK/platform-tools:/Users/lelong37/Library/Android-SDK/tools:/usr/local/lib/dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin:/Users/lelong37/.dnx/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/scmobileapp/Resources/user_profileimage@3x.png /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/build/emulator/scmobileapp.app
CpResource scmobileapp/Resources/user_profileimage@3x.png build/emulator/scmobileapp.app/user_profileimage@3x.png
    cd /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/lelong37/.nvm/versions/node/v4.2.1/bin:/Applications/Genymotion\\ Shell.app/Contents/MacOS/:/Applications/Genymotion.app/Contents/MacOS:/Users/lelong37/Library/Android-SDK/platform-tools:/Users/lelong37/Library/Android-SDK/tools:/usr/local/lib/dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin:/Users/lelong37/.dnx/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/scmobileapp/Resources/user_profileimage@3x.png /Users/lelong37/Sources/sc11/scmobile-app/platforms/ios/build/emulator/scmobileapp.app
  ›Command failed: The debug process exited unexpectedly code:null
Command failed: The debug process exited unexpectedly code:null
  ›Error: The debug process exited unexpectedly code:null
    at Object.errP (/Users/lelong37/.vscode/extensions/Telerik.nativescript-0.1.1/out/webkit/utilities.js:369:13)
    at /Users/lelong37/.vscode/extensions/Telerik.nativescript-0.1.1/out/webkit/webKitDebugAdapter.js:68:26
    at process._tickCallback (node.js:369:9)
  ›To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"[NativeScript-Debug-Adapter] The debug process exited unexpectedly code:null"}
  ›From client: disconnect({"restart":false})
  ›To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
```

**Comment by ivanbuhov** [comment] 2016-03-10 09:57
It seems VS Code 0.10.10 comes with some breaking changes. We are working on fixes of these issues but they will be included in the next version of the extension. It will be published as soon as possible. Till then I suggest you downgrading to VS Code 0.10.9.

@lelong37 I can't reproduce the issue. What is the result of executing `tns debug ios --emulator` from the command line? Can you debug the app with the NativeScript Inspector app.

**Comment by ivanbuhov** [comment] 2016-03-11 08:47
I am locking this issue in favor of these:
https://github.com/NativeScript/nativescript-vscode-extension/issues/27
https://github.com/NativeScript/nativescript-vscode-extension/issues/28
https://github.com/NativeScript/nativescript-vscode-extension/issues/29

**Comment by burkeholland** [comment] 2016-03-13 14:22
@lelong37 I had that same error and it was because i was trying to run on my device when my device wasn't attached.

**Comment by ivanbuhov** [comment] 2016-03-14 15:48
NativeScript for VSCode v0.2.0 is live in the VS Code marketplace. It supports VS Code 0.10.10.

**Closed by ivanbuhov** 2016-03-14 15:48 UTC

**Comment by sitefinitysteve** [comment] 2016-03-14 15:51
@ivanbuhov Anything new or just fix the incompatibilities?

**Comment by ivanbuhov** [comment] 2016-03-14 15:51
@sitefinitysteve https://github.com/NativeScript/nativescript-vscode-extension/blob/master/CHANGELOG.md
