### ISSUE TITLE
0.5.0 Doesn't hit breakpoints on Launch/Sync

### ISSUE THREAD

**Issue by rLoka** [NativeScript/nativescript-vscode-extension#101] opened 2016-12-11 15:17 UTC
As can be seen in screenshot, debug doesn't hit breakpoints, usually happens after one successful debug. Then I have to restart the computer to make debug hit breakpoints on debug. I am using Ubuntu 16.10.

![screenshot from 2016-12-11 15-55-48](https://cloud.githubusercontent.com/assets/9071942/21080936/d2f012a8-bfbb-11e6-953d-780b38e64a66.png)

```
tns info
All NativeScript components versions information
┌──────────────────┬───────────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version       │ Latest version │ Information      │
│ nativescript     │ 2.5.0-2016-12-06-7346 │ 2.4.2          │ Up to date       │
│ tns-core-modules │ 2.4.1                 │ 2.4.2          │ Update available │
│ tns-android      │ 2.4.1                 │ 2.4.1          │ Up to date       │
│ tns-ios          │ 2.3.0                 │ 2.4.0          │ Update available │
└──────────────────┴───────────────────────┴────────────────┴──────────────────┘
```

Relevant part of diagnostic debug:

```
_findSourceMapUrlInFile: source map url at end of generated file '/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/label/label-common.js''
SourceMaps.createSourceMap: Could not read map from /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/label/label-common.js.map
From target(event): {"seq":98,"type":"event","event":"afterCompile","success":true,"body":{"script":{"handle":1,"type":"script","name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/text-base/text-base.js","id":160,"lineOffset":0,"columnOffset":0,"lineCount":24,"sourceStart":"(function(module, exports, require, __filename, __dirname){ var common = require","sourceLength":831,"scriptType":2,"compilationType":0,"context":{"ref":0},"text":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/text-base/text-base.js (lines: 24)"}},"refs":[{"handle":0,"type":"context","text":"#<ContextMirror>"}],"running":true}
Paths.scriptParsed: resolved /data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/text-base/text-base.js to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/text-base/text-base.android.js. webRoot: /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker
_findSourceMapUrlInFile: source map url at end of generated file '/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/text-base/text-base.android.js''
SourceMaps.createSourceMap: Could not read map from /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/text-base/text-base.android.js.map
From target(event): {"seq":99,"type":"event","event":"afterCompile","success":true,"body":{"script":{"handle":1,"type":"script","name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/text-base/text-base-common.js","id":161,"lineOffset":0,"columnOffset":0,"lineCount":124,"sourceStart":"(function(module, exports, require, __filename, __dirname){ var view = require(\"","sourceLength":5007,"scriptType":2,"compilationType":0,"context":{"ref":0},"text":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/text-base/text-base-common.js (lines: 124)"}},"refs":[{"handle":0,"type":"context","text":"#<ContextMirror>"}],"running":true}
Paths.scriptParsed: resolved /data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/text-base/text-base-common.js to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/text-base/text-base-common.js. webRoot: /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker
_findSourceMapUrlInFile: source map url at end of generated file '/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/text-base/text-base-common.js''
SourceMaps.createSourceMap: Could not read map from /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/text-base/text-base-common.js.map
From target(event): {"seq":100,"type":"event","event":"afterCompile","success":true,"body":{"script":{"handle":1,"type":"script","name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/text/formatted-string.js","id":162,"lineOffset":0,"columnOffset":0,"lineCount":35,"sourceStart":"(function(module, exports, require, __filename, __dirname){ var formattedStringC","sourceLength":1441,"scriptType":2,"compilationType":0,"context":{"ref":0},"text":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/text/formatted-string.js (lines: 35)"}},"refs":[{"handle":0,"type":"context","text":"#<ContextMirror>"}],"running":true}
Paths.scriptParsed: resolved /data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/text/formatted-string.js to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/text/formatted-string.android.js. webRoot: /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker
_findSourceMapUrlInFile: source map url at end of generated file '/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/text/formatted-string.android.js''
SourceMaps.createSourceMap: Could not read map from /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/text/formatted-string.android.js.map
From target(event): {"seq":101,"type":"event","event":"afterCompile","success":true,"body":{"script":{"handle":1,"type":"script","name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/text/formatted-string-common.js","id":163,"lineOffset":0,"columnOffset":0,"lineCount":239,"sourceStart":"(function(module, exports, require, __filename, __dirname){ var observable = req","sourceLength":8227,"scriptType":2,"compilationType":0,"context":{"ref":0},"text":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/text/formatted-string-common.js (lines: 239)"}},"refs":[{"handle":0,"type":"context","text":"#<ContextMirror>"}],"running":true}
Paths.scriptParsed: resolved /data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/text/formatted-string-common.js to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/text/formatted-string-common.js. webRoot: /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker
_findSourceMapUrlInFile: source map url at end of generated file '/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/text/formatted-string-common.js''
SourceMaps.createSourceMap: Could not read map from /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/text/formatted-string-common.js.map
From target(event): {"seq":102,"type":"event","event":"afterCompile","success":true,"body":{"script":{"handle":1,"type":"script","name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/data/observable-array/observable-array.js","id":164,"lineOffset":0,"columnOffset":0,"lineCount":192,"sourceStart":"(function(module, exports, require, __filename, __dirname){ var observable = req","sourceLength":7011,"scriptType":2,"compilationType":0,"context":{"ref":0},"text":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/data/observable-array/observable-array.js (lines: 192)"}},"refs":[{"handle":0,"type":"context","text":"#<ContextMirror>"}],"running":true}
Paths.scriptParsed: resolved /data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/data/observable-array/observable-array.js to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/data/observable-array/observable-array.js. webRoot: /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker
_findSourceMapUrlInFile: source map url at end of generated file '/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/data/observable-array/observable-array.js''
SourceMaps.createSourceMap: Could not read map from /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/data/observable-array/observable-array.js.map
From target(event): {"seq":103,"type":"event","event":"afterCompile","success":true,"body":{"script":{"handle":1,"type":"script","name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/text-base/text-base-styler.js","id":165,"lineOffset":0,"columnOffset":0,"lineCount":122,"sourceStart":"(function(module, exports, require, __filename, __dirname){ var utils = require(","sourceLength":6473,"scriptType":2,"compilationType":0,"context":{"ref":0},"text":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/text-base/text-base-styler.js (lines: 122)"}},"refs":[{"handle":0,"type":"context","text":"#<ContextMirror>"}],"running":true}
Paths.scriptParsed: resolved /data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/text-base/text-base-styler.js to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/text-base/text-base-styler.android.js. webRoot: /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker
_findSourceMapUrlInFile: source map url at end of generated file '/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/text-base/text-base-styler.android.js''
SourceMaps.createSourceMap: Could not read map from /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/text-base/text-base-styler.android.js.map
From target(event): {"seq":104,"type":"event","event":"afterCompile","success":true,"body":{"script":{"handle":1,"type":"script","name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/button/button.js","id":166,"lineOffset":0,"columnOffset":0,"lineCount":106,"sourceStart":"(function(module, exports, require, __filename, __dirname){ var common = require","sourceLength":5071,"scriptType":2,"compilationType":0,"context":{"ref":0},"text":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/button/button.js (lines: 106)"}},"refs":[{"handle":0,"type":"context","text":"#<ContextMirror>"}],"running":true}
Paths.scriptParsed: resolved /data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/button/button.js to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/button/button.android.js. webRoot: /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker
_findSourceMapUrlInFile: source map url at end of generated file '/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/button/button.android.js''
SourceMaps.createSourceMap: Could not read map from /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/button/button.android.js.map
From target(event): {"seq":105,"type":"event","event":"afterCompile","success":true,"body":{"script":{"handle":1,"type":"script","name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/button/button-common.js","id":167,"lineOffset":0,"columnOffset":0,"lineCount":126,"sourceStart":"(function(module, exports, require, __filename, __dirname){ var dependency_obser","sourceLength":5266,"scriptType":2,"compilationType":0,"context":{"ref":0},"text":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/button/button-common.js (lines: 126)"}},"refs":[{"handle":0,"type":"context","text":"#<ContextMirror>"}],"running":true}
Paths.scriptParsed: resolved /data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/button/button-common.js to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/button/button-common.js. webRoot: /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker
_findSourceMapUrlInFile: source map url at end of generated file '/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/button/button-common.js''
SourceMaps.createSourceMap: Could not read map from /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/button/button-common.js.map
From target(event): {"seq":106,"type":"event","event":"afterCompile","success":true,"body":{"script":{"handle":1,"type":"script","name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/frame/fragment.js","id":168,"lineOffset":0,"columnOffset":0,"lineCount":45,"sourceStart":"(function(module, exports, require, __filename, __dirname){ var frame_1 = requir","sourceLength":2046,"scriptType":2,"compilationType":0,"context":{"ref":0},"text":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/frame/fragment.js (lines: 45)"}},"refs":[{"handle":0,"type":"context","text":"#<ContextMirror>"}],"running":true}
Paths.scriptParsed: resolved /data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/ui/frame/fragment.js to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/frame/fragment.android.js. webRoot: /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker
_findSourceMapUrlInFile: source map url at end of generated file '/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/frame/fragment.android.js''
SourceMaps.createSourceMap: Could not read map from /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/ui/frame/fragment.android.js.map
From target(event): {"seq":0,"type":"event","event":"messageAdded","success":true,"body":{"message":{"source":"console-api","type":"log","level":"log","line":42,"column":17,"url":"\/data\/data\/org.nativescript.OfficeEquipmentTracker\/files\/app\/ViewModels\/MainViewModel.js","groupLevel":7,"repeatCount":1,"text":"Baza inicijalizirana!"}}}
Baza inicijalizirana! (/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/ViewModels/MainViewModel.js:42:17)
From target(event): {"seq":0,"type":"event","event":"messageAdded","success":true,"body":{"message":{"source":"console-api","type":"log","level":"log","line":46,"column":17,"url":"\/data\/data\/org.nativescript.OfficeEquipmentTracker\/files\/app\/ViewModels\/MainViewModel.js","groupLevel":7,"repeatCount":1,"text":"Tablice kreirane!"}}}
Tablice kreirane! (/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/ViewModels/MainViewModel.js:46:17)
From target(event): {"seq":107,"type":"event","event":"afterCompile","success":true,"body":{"script":{"handle":1,"type":"script","name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/xhr/xhr.js","id":169,"lineOffset":0,"columnOffset":0,"lineCount":324,"sourceStart":"(function(module, exports, require, __filename, __dirname){ var http = require(\"","sourceLength":11345,"scriptType":2,"compilationType":0,"context":{"ref":0},"text":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/xhr/xhr.js (lines: 324)"}},"refs":[{"handle":0,"type":"context","text":"#<ContextMirror>"}],"running":true}
Paths.scriptParsed: resolved /data/data/org.nativescript.OfficeEquipmentTracker/files/app/tns_modules/xhr/xhr.js to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/xhr/xhr.js. webRoot: /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker
_findSourceMapUrlInFile: source map url at end of generated file '/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/xhr/xhr.js''
SourceMaps.createSourceMap: Could not read map from /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/node_modules/tns-core-modules/xhr/xhr.js.map
From target(event): {"seq":0,"type":"event","event":"messageAdded","success":true,"body":{"message":{"source":"console-api","type":"log","level":"log","line":50,"column":17,"url":"\/data\/data\/org.nativescript.OfficeEquipmentTracker\/files\/app\/ViewModels\/MainViewModel.js","groupLevel":7,"repeatCount":1,"text":"Podaci sinkronizirani!"}}}
Podaci sinkronizirani! (/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/ViewModels/MainViewModel.js:50:17)
From target(event): {"seq":0,"type":"event","event":"messageAdded","success":true,"body":{"message":{"source":"console-api","type":"log","level":"log","line":56,"column":17,"url":"\/data\/data\/org.nativescript.OfficeEquipmentTracker\/files\/app\/ViewModels\/MainViewModel.js","groupLevel":7,"repeatCount":1,"text":"[object Object]"}}}
[object Object] (/home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/ViewModels/MainViewModel.js:56:17)
From target(response): {"seq":108,"request_seq":1,"type":"response","command":"setbreakpoint","success":true,"body":{"type":"scriptName","breakpoint":1,"script_name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/Common/Data/Database.js","line":76,"column":24,"actual_locations":[{"line":76,"column":24,"script_id":137}]},"refs":[],"running":true}
From target(response): {"seq":109,"request_seq":2,"type":"response","command":"setbreakpoint","success":true,"body":{"type":"scriptName","breakpoint":2,"script_name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/Common/Data/Database.js","line":78,"column":24,"actual_locations":[{"line":78,"column":24,"script_id":137}]},"refs":[],"running":true}
SourceMaps.setBP: Mapped /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/Common/Data/Database.js:76:24 to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/Common/Data/Database.ts:128
SourceMaps.setBP: Mapped /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/Common/Data/Database.js:78:24 to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/Common/Data/Database.ts:130
To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":true,"line":129},{"verified":true,"line":131}]}}
To target: {"seq":3,"type":"request","command":"setbreakpoint","arguments":{"type":"script","target":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/ViewModels/MainViewModel.js","line":55,"column":8,"ignoreCount":0}}
To target: {"seq":4,"type":"request","command":"setbreakpoint","arguments":{"type":"script","target":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/ViewModels/MainViewModel.js","line":52,"column":8,"ignoreCount":0}}
To target: {"seq":5,"type":"request","command":"setbreakpoint","arguments":{"type":"script","target":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/ViewModels/MainViewModel.js","line":49,"column":8,"ignoreCount":0}}
To client: {"seq":0,"type":"response","request_seq":4,"command":"setBreakpoints","success":true,"body":{"breakpoints":[]}}
From target(response): {"seq":110,"request_seq":3,"type":"response","command":"setbreakpoint","success":true,"body":{"type":"scriptName","breakpoint":3,"script_name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/ViewModels/MainViewModel.js","line":55,"column":8,"actual_locations":[{"line":55,"column":8,"script_id":134}]},"refs":[],"running":true}
From target(response): {"seq":111,"request_seq":4,"type":"response","command":"setbreakpoint","success":true,"body":{"type":"scriptName","breakpoint":4,"script_name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/ViewModels/MainViewModel.js","line":52,"column":8,"actual_locations":[{"line":52,"column":8,"script_id":134}]},"refs":[],"running":true}
From target(response): {"seq":112,"request_seq":5,"type":"response","command":"setbreakpoint","success":true,"body":{"type":"scriptName","breakpoint":5,"script_name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/ViewModels/MainViewModel.js","line":49,"column":8,"actual_locations":[{"line":49,"column":8,"script_id":134}]},"refs":[],"running":true}
SourceMaps.setBP: Mapped /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/ViewModels/MainViewModel.js:55:8 to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/ViewModels/MainViewModel.ts:67
SourceMaps.setBP: Mapped /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/ViewModels/MainViewModel.js:52:8 to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/ViewModels/MainViewModel.ts:63
SourceMaps.setBP: Mapped /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/ViewModels/MainViewModel.js:49:8 to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/ViewModels/MainViewModel.ts:60
To target: {"seq":6,"type":"request","command":"setbreakpoint","arguments":{"type":"script","target":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/Common/Data/ObjectRelationalMapper.js","line":46,"column":12,"ignoreCount":0}}
To client: {"seq":0,"type":"response","request_seq":5,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":true,"line":68},{"verified":true,"line":64},{"verified":true,"line":61}]}}
From target(response): {"seq":113,"request_seq":6,"type":"response","command":"setbreakpoint","success":true,"body":{"type":"scriptName","breakpoint":6,"script_name":"/data/data/org.nativescript.OfficeEquipmentTracker/files/app/Common/Data/ObjectRelationalMapper.js","line":46,"column":12,"actual_locations":[{"line":46,"column":12,"script_id":146}]},"refs":[],"running":true}
SourceMaps.setBP: Mapped /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/Common/Data/ObjectRelationalMapper.js:46:12 to /home/rloka/Desktop/Faks/AiR/OfficeEquipmentTracker/OfficeEquipmentTracker/app/Common/Data/ObjectRelationalMapper.ts:54
To client: {"seq":0,"type":"response","request_seq":6,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":true,"line":55}]}}
From client: setExceptionBreakpoints({"filters":["uncaught"]})
To target: {"seq":7,"type":"request","command":"setexceptionbreak","arguments":{"type":"uncaught","enabled":true}}
From target(response): {"seq":114,"request_seq":7,"type":"response","command":"setexceptionbreak","success":true,"body":{"type":"uncaught","enabled":true},"refs":[],"running":true}
To client: {"seq":0,"type":"response","request_seq":7,"command":"setExceptionBreakpoints","success":true}
From client: configurationDone(undefined)
To client: {"seq":0,"type":"response","request_seq":8,"command":"configurationDone","success":true}

```

**Comment by pkoleva** [comment] 2017-05-17 12:44
Hey @rLoka,
Do you still have this problem with the latest versions of the CLI (3.0.1) and NS Extension (0.7.0)?

**Comment by rLoka** [comment] 2017-05-17 17:43
@pkoleva Not currently working with Nativescript anymore.

**Comment by pkoleva** [comment] 2017-05-18 07:49
Thanks for the quick reply! 
Since I am not able to reproduce it with our latest versions I'll close the issue. If you come across it again do not hesitate to reopen it, comment here or open a new one!

**Closed by pkoleva** 2017-05-18 07:49 UTC
Labels: android, bug
