### ISSUE TITLE
Global scope not populated when expanded on Android

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-vscode-extension#21] opened 2016-02-29 12:49 UTC
https://nativescript.slack.com/files/danwilson/F0P9JH45Q/pasted_image_at_2016_02_26_04_24_pm.png

**Comment by sipacate** [comment] 2016-02-29 12:52
Here is a screenshot of iOS showing the global scope populated.
![ios global is populated](https://cloud.githubusercontent.com/assets/1827394/13394933/695d4a2e-deb9-11e5-990d-48c8dcec287a.png)

**Comment by ivanbuhov** [comment] 2016-04-13 08:29
The same is happening when debugging an Android app with node inspector via `tns debug android`. I guess the problem is in the debugger backend.

**Comment by toddanglin** [comment] 2017-01-30 16:37
Following-up on the [Twitter dialog](https://twitter.com/nativescript/status/826094540121452544), it seems fixing this bug would enable "auto generation" of NativeScript plugins from native iOS and Android libraries. If that is the case, that's a great reason to see this bug addressed. Would make it much easier to expand NativeScript plugin library.

**Comment by ivanbuhov** [comment] 2017-01-30 17:03
As far as I can remember, there were some technical difficulties to enable this functionality in the Android runtime with the old `v8 remote debug protocol`. Since android runtime v2.5, `Chrome Debugging Protocol` is the default one, we have to check if this change makes the issue easier to resolve.
ping @Plamen5kov @Pip3r4o

**Comment by Pip3r4o** [comment] 2017-01-31 08:18
I'll have a look

**Comment by Pip3r4o** [comment] 2017-02-21 14:47
This is addressed with https://github.com/NativeScript/android-runtime/pull/714 which will be available in `@next` soon, and officially released in `3.0.0`

![variables-vscode](https://cloud.githubusercontent.com/assets/10464986/23169697/73f8027e-f855-11e6-8e64-732a0d845094.PNG)

**Closed** 2017-03-17 12:09 UTC
Labels: android, bug
