### ISSUE TITLE
Error: Set breakpoints request timed out

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-vscode-extension#196] opened 2018-08-02 13:31 UTC
Steps:
- `npm link tns-core-modules`
- `Launch on iOS` of [safe-area](https://github.com/NativeScript/NativeScript/tree/ios-safe-area/e2e/safe-area) app
- set a breakpoint at [here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view/view.ios.ts#L179)
- hover 2 lines above on `const nativeView`

Error:
```
(CoreFoundation) -[UIView collisionBoundingPath]: unrecognized selector sent to instance 0x7fbfff734360
Error: Set breakpoints request timed out
    at Timeout.setTimeout [as _onTimeout] (/Users/chimev/.vscode/extensions/telerik.nativescript-0.8.0/node_modules/vscode-chrome-debug-core/out/src/utils.js:71:24)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

Versions:
```
$ node -v
v8.11.3
$ npm -v
5.6.0
$ tns --version
4.1.2
```
NativeScript VSCode Extension 0.8.0.

**Comment by MartoYankov** [comment] 2018-08-14 11:50
Closing - caused by https://github.com/NativeScript/nativescript-vscode-extension/issues/198

**Closed by MartoYankov** 2018-08-14 11:50 UTC
