### ISSUE TITLE
VS Code debugger not working in iOS

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/nativescript-vscode-extension#84] opened 2016-09-30 02:49 UTC
Debugger stops after "app.js" and app "launchscreen" then nothing happens.

It works from terminal.

System configuration: NativeScript 2.3.0, OS X 10.12 Sierra, iOS 10

**Comment by ivanbuhov** [comment] 2016-09-30 07:45
@alexrainman It seems your problem is related to https://github.com/NativeScript/ios-runtime/issues/655. The issue is related to `nativescript-core-modules` and there is a [fix merged in the master branch of the modules](https://github.com/NativeScript/NativeScript/pull/2744). Updating to @next version of the `nativescript-core-modules` package should fix the issue. You can read more [here](https://docs.nativescript.org/releases/running-latest) on how to use the latest bits.

**Comment by pkoleva** [comment] 2017-05-17 12:40
Closing the issue due to lack of response. 
If you encounter it again reopen it, open a new one or comment with detailed steps to reproduce.

**Closed by pkoleva** 2017-05-17 12:40 UTC
