### ISSUE TITLE
Run + Attach on Android

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/nativescript-vscode-extension#46] opened 2016-05-16 14:23 UTC
Running an app on android emulator (using `Run on Android` command) and after that attaching with `Attach on Android Emulator` configuration fails with `Connection timed out`.

**Comment by emankovski** [comment] 2016-05-16 18:20
+

**Comment by chimon2000** [comment] 2016-05-16 18:22
+1

**Comment by chimon2000** [comment] 2016-05-16 18:54
+1 For me this happens when I use the babel hook.

**Comment by nicHoch** [comment] 2016-06-11 11:19
+1 but only if i "Attach on Android Device"

```
Getting debug port
device: 9edfd1d8 debug port: 40000
Preparing for debug
Attaching to debug application
Command failed: Connection timed out
Closing debug connection
Terminating debug session
```
would be very nice if that would be available again. 
Thanks Nicky

**Comment by javierRamosCondes** [comment] 2016-06-12 15:19
+1 attaching on Android device.
`Getting debug port
device: 192.168.56.101:5555 debug port: 40000
Preparing for debug
Attaching to debug application
Command failed: Connection timed out
Closing debug connection
Terminating debug session`

**Comment by bijeebuss** [comment] 2016-06-27 14:53
Mine is doing the same
`Getting debug port
device: emulator-5554 debug port: 40000
Preparing for debug
Attaching to debug application
Command failed: Connection timed out
Closing debug connection
Terminating debug session`

**Comment by techguysyoo** [comment] 2016-10-03 09:56
Having the same issue when doing "launch with android"-
Command failed: Can't connect. Check the application is running on the device

**Comment by TeddyBo** [comment] 2016-10-03 17:24
+1. Have the same error. But it works if I start my app from terminal and then debug with "request": "attach"

**Comment by NgSculptor** [comment] 2016-11-22 06:01
+1

**Comment by EddyVerbruggen** [comment] 2018-02-06 21:15
I've tried to reproduce this with 0.7.2 and honestly can't reproduce it. I tried `tns create test` and `tns create test2 --tsc` (the latter is TS based, so has hooks).

The I ran the apps and attached successfully to the running processes. I also ran on Android from the debugger dropdown and again everything seems fine.

So please reopen if you're on 0.7.2 (or newer) if you still experience this issue, but when doing so, please also include a demo app reproducing the issue so we can take an even closer look.

**Closed by EddyVerbruggen** 2018-02-06 21:15 UTC
Labels: bug, os: android
