### ISSUE TITLE
Launch on android, unverified breakpoint issue

### ISSUE THREAD

**Issue by kelinwu** [NativeScript/nativescript-vscode-extension#152] opened 2018-01-09 15:25 UTC
I am having debugging issue in VSCODE with nativescript extension(0.7.2) typically when try to debug the script in real android phones. it simply don't hit the breakpoints. I have stopOnEntry:true in launch.json however that wont help. any idea?

**Comment by Plamen5kov** [comment] 2018-01-10 13:49
Hi @kelinwu, I'm sorry you have issues with the ns vscode extension!
As a temporary workaround I can suggest writing `debugger;` statement in the code and see if the breakpoints will hit. 
Is the problem occurring only for real devices or is it reproducible for emulators also?

**Comment by kelinwu** [comment] 2018-01-10 16:14
adding debugger didn't help as well. this problem starts since day one, I just wondering if anyone else ever tried to debug with a real phone? what is the outcome? thanks!

**Comment by Plamen5kov** [comment] 2018-01-11 08:37
@kelinwu I couldn't reproduce your issue. Could you provide an example project with steps to reproduce, so I can help you figure out the problem?

**Comment by hshristov** [comment] 2018-01-12 07:45
@kelinwu I have similar issues on a random cases. What I do most of the time
 - put `stopOnEntry: true` in the `launch.json`
 - when app starts it stops inside ts_helpers.js. Then first disable and enable all breakpoints from VS Code button then hit F5 to continue program execution. Sometimes it is good to delete `platforms` folder in case some files are not synced and also uninstall application from device/simulator.

Hope it helps.

**Comment by Plamen5kov** [comment] 2018-01-15 11:29
closing as a duplicate of: https://github.com/NativeScript/nativescript-vscode-extension/issues/143

**Closed by Plamen5kov** 2018-01-15 11:29 UTC
