### ISSUE TITLE
Debug via extension broken with VSCode 1.20

### ISSUE THREAD

**Issue by Andrea65** [NativeScript/nativescript-vscode-extension#158] opened 2018-02-09 20:16 UTC
Cannot run "Launch on android" nor "Attach on Android" after updating Visual Studio Code to version 1.2ù
Any workaround?

**Comment by cfirmo33** [comment] 2018-02-13 15:18
waiting for this correction too.

**Comment by EddyVerbruggen** [comment] 2018-02-13 15:39
Wondering if this is Windows-only.

Does anyone see this on macOS? I'm running VSCode 1.2 on macOS and extension version 0.7.2 and can attach/launch on Android just fine.

**Comment by NickIliev** [comment] 2018-02-13 16:03
@EddyVerbruggen I've experienced this one on macOS as well. 
However, the issue is not consistent on Mac while on Windows it is 100% reproducible

**Comment by EddyVerbruggen** [comment] 2018-02-14 15:20
Hmm, macOS is rock solid for me (and I don't *currently* have a Windows machine at hand). For anyone experiencing this issue: I wonder if it would help if you change this in `launch.json`:

```json
        {
            "name": "Launch on Android",
            "type": "nativescript",
            "request": "launch",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true,
        },
```

to

```json
        {
            "name": "Launch on Android",
            "tnsArgs": [
                "--debug-brk=true"
            ],
            "type": "nativescript",
            "request": "launch",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true,
        },
```

so add that `tnsArgs` bit.

**Comment by tedekeroth** [comment] 2018-02-15 13:17
Hey,
running win7, Vscode 1.20.1. Tried both --debug-brk and --debug, no change for me at least.

**Comment by Andrea65** [comment] 2018-02-15 13:56
Just to clarify, the problem is not debugging.
When you click 'Launch on Android' nothing happens. The debug console window remains empty, with no [NSDegugAdapter] shown.

**Comment by EddyVerbruggen** [comment] 2018-02-16 20:43
Thanks for the feedback! Knowing that adding `--debug(-brk)` didn't help made me install a virtual Windows machine on my Mac to reproduce this issue myself.

After some fooling around in the codebase and trying to wrap my head around how the debugger server and client communicate (sockets, in this case) I found the issue and a solution... so expect a PR real soon.

**Comment by EddyVerbruggen** [comment] 2018-02-16 22:33
⬆️ PR pending 🎉

**Comment by thaoula** [comment] 2018-02-21 07:26
That is great news!!! When can we expect the PR to merged?

Currently debugging with the Chrome Dev tools is not an awesome experience.

**Closed** 2018-02-23 09:01 UTC
Labels: bug, os: android

**Comment by thaoula** [comment] 2018-02-24 02:46
When will a new version of the Nativescript extension with theses fixes be pushed out?

**Comment by etabakov** [comment] 2018-02-24 13:04
We are aiming to release it early next week. Meanwhile, you can try the latest bits by building the extensions from the latest master branch. There were already tested and no issues were found.

**Comment by EddyVerbruggen** [comment] 2018-02-24 18:42
Cool! Thanks for merging this @etabakov 👍

**Comment by etabakov** [comment] 2018-02-24 21:43
We thank you for the help with this issue 💯

**Comment by etabakov** [comment] 2018-02-27 14:52
A new version was just published. Let us know how it goes!

**Comment by thaoula** [comment] 2018-03-02 08:19
Hi @etabakov,

So I can now debug and vscode does not hang. However, quite frequently the process will timeout and debugging does not work.

I have also noticed node-sass is left running in the background, one for each time i try and use the debug function in vscode.

if I dont kills the node-sass process it will cause loop through transferring the files to the similator several times before you see broken app (css broken) and the following error in the console.

Error: Css styling failed: Error: undefined:1:16: missing '{'

I am running on Mac OS High Sierra and mainly trying to connect to IOS.

Regards,
Tarek

**Comment by etabakov** [comment] 2018-03-02 08:51
Hey Tarek, 

I believe these are separate issues that are not relevant to the problem that we solved in this issue. Can you open a separate issue and we will try to look at it? Also, I think there is a very similar issue reported already in a separate thread: https://github.com/NativeScript/nativescript-cli/issues/3235

Thanks,
Emil

**Comment by thaoula** [comment] 2018-03-02 09:34
Hi Emil,

I was also having a problem debugging with VS code up until this patch. Try to debug did nothing or hung vscode.

Regards,
Tarek

**Comment by thaoula** [comment] 2018-03-02 09:37
Hi @etabakov,

The last post on the issue use suggested was from me... can someone assist?

Regards,
Tarek

**Comment by etabakov** [comment] 2018-03-02 09:41
We are currently working on a Release Candidate for 4.0 and the team is focused entirely on this task. After that we will probably be able to take a look at the issue and get back to you.

**Comment by thaoula** [comment] 2018-03-02 09:45
Thank you very much. Looking forward to V4
